window.GERMAN_WORDS = [
  // FOOD (30)
  { word_de: "das Brot", forms: { plural: "die Brote" }, word_en: "bread", category: "food" },
  { word_de: "der Apfel", forms: { plural: "die Äpfel" }, word_en: "apple", category: "food" },
  { word_de: "die Banane", forms: { plural: "die Bananen" }, word_en: "banana", category: "food" },
  { word_de: "die Orange", forms: { plural: "die Orangen" }, word_en: "orange", category: "food" },
  { word_de: "die Erdbeere", forms: { plural: "die Erdbeeren" }, word_en: "strawberry", category: "food" },
  { word_de: "die Tomate", forms: { plural: "die Tomaten" }, word_en: "tomato", category: "food" },
  { word_de: "die Kartoffel", forms: { plural: "die Kartoffeln" }, word_en: "potato", category: "food" },
  { word_de: "die Karotte", forms: { plural: "die Karotten" }, word_en: "carrot", category: "food" },
  { word_de: "das Fleisch", forms: { plural: null }, word_en: "meat", category: "food" },
  { word_de: "der Fisch", forms: { plural: "die Fische" }, word_en: "fish", category: "food" },
  { word_de: "die Milch", forms: { plural: null }, word_en: "milk", category: "food" },
  { word_de: "der Käse", forms: { plural: "die Käse" }, word_en: "cheese", category: "food" },
  { word_de: "der Joghurt", forms: { plural: "die Joghurts" }, word_en: "yogurt", category: "food" },
  { word_de: "die Butter", forms: { plural: null }, word_en: "butter", category: "food" },
  { word_de: "das Ei", forms: { plural: "die Eier" }, word_en: "egg", category: "food" },
  { word_de: "der Reis", forms: { plural: null }, word_en: "rice", category: "food" },
  { word_de: "die Nudeln", forms: { plural: null }, word_en: "pasta", category: "food" },
  { word_de: "das Salz", forms: { plural: null }, word_en: "salt", category: "food" },
  { word_de: "der Zucker", forms: { plural: null }, word_en: "sugar", category: "food" },
  { word_de: "das Wasser", forms: { plural: null }, word_en: "water", category: "food" },
  { word_de: "der Kaffee", forms: { plural: null }, word_en: "coffee", category: "food" },
  { word_de: "der Tee", forms: { plural: null }, word_en: "tea", category: "food" },
  { word_de: "die Suppe", forms: { plural: "die Suppen" }, word_en: "soup", category: "food" },
  { word_de: "der Salat", forms: { plural: "die Salate" }, word_en: "salad", category: "food" },
  { word_de: "das Gemüse", forms: { plural: null }, word_en: "vegetables", category: "food" },
  { word_de: "das Obst", forms: { plural: null }, word_en: "fruit", category: "food" },
  { word_de: "die Pizza", forms: { plural: "die Pizzen" }, word_en: "pizza", category: "food" },
  { word_de: "der Hamburger", forms: { plural: "die Hamburger" }, word_en: "hamburger", category: "food" },
  { word_de: "die Wurst", forms: { plural: "die Würste" }, word_en: "sausage", category: "food" },
  { word_de: "das Abendessen", forms: { plural: null }, word_en: "dinner", category: "food" },

  // ANIMALS (30)
  { word_de: "der Hund", forms: { plural: "die Hunde" }, word_en: "dog", category: "animals" },
  { word_de: "die Katze", forms: { plural: "die Katzen" }, word_en: "cat", category: "animals" },
  { word_de: "der Vogel", forms: { plural: "die Vögel" }, word_en: "bird", category: "animals" },
  { word_de: "die Maus", forms: { plural: "die Mäuse" }, word_en: "mouse", category: "animals" },
  { word_de: "die Ente", forms: { plural: "die Enten" }, word_en: "duck", category: "animals" },
  { word_de: "das Pferd", forms: { plural: "die Pferde" }, word_en: "horse", category: "animals" },
  { word_de: "die Kuh", forms: { plural: "die Kühe" }, word_en: "cow", category: "animals" },
  { word_de: "das Schwein", forms: { plural: "die Schweine" }, word_en: "pig", category: "animals" },
  { word_de: "das Schaf", forms: { plural: "die Schafe" }, word_en: "sheep", category: "animals" },
  { word_de: "die Ziege", forms: { plural: "die Ziegen" }, word_en: "goat", category: "animals" },
  { word_de: "der Löwe", forms: { plural: "die Löwen" }, word_en: "lion", category: "animals" },
  { word_de: "der Tiger", forms: { plural: "die Tiger" }, word_en: "tiger", category: "animals" },
  { word_de: "der Bär", forms: { plural: "die Bären" }, word_en: "bear", category: "animals" },
  { word_de: "der Fuchs", forms: { plural: "die Füchse" }, word_en: "fox", category: "animals" },
  { word_de: "der Wolf", forms: { plural: "die Wölfe" }, word_en: "wolf", category: "animals" },
  { word_de: "der Hase", forms: { plural: "die Hasen" }, word_en: "rabbit", category: "animals" },
  { word_de: "das Kaninchen", forms: { plural: "die Kaninchen" }, word_en: "bunny", category: "animals" },
  { word_de: "der Affe", forms: { plural: "die Affen" }, word_en: "monkey", category: "animals" },
  { word_de: "der Elefant", forms: { plural: "die Elefanten" }, word_en: "elephant", category: "animals" },
  { word_de: "die Giraffe", forms: { plural: "die Giraffen" }, word_en: "giraffe", category: "animals" },
  { word_de: "der Pinguin", forms: { plural: "die Pinguine" }, word_en: "penguin", category: "animals" },
  { word_de: "der Delfin", forms: { plural: "die Delfine" }, word_en: "dolphin", category: "animals" },
  { word_de: "der Wal", forms: { plural: "die Wale" }, word_en: "whale", category: "animals" },
  { word_de: "der Hai", forms: { plural: "die Haie" }, word_en: "shark", category: "animals" },
  { word_de: "die Schlange", forms: { plural: "die Schlangen" }, word_en: "snake", category: "animals" },
  { word_de: "die Schildkröte", forms: { plural: "die Schildkröten" }, word_en: "turtle", category: "animals" },
  { word_de: "die Spinne", forms: { plural: "die Spinnen" }, word_en: "spider", category: "animals" },
  { word_de: "die Biene", forms: { plural: "die Bienen" }, word_en: "bee", category: "animals" },
  { word_de: "die Ameise", forms: { plural: "die Ameisen" }, word_en: "ant", category: "animals" },
  { word_de: "die Fliege", forms: { plural: "die Fliegen" }, word_en: "fly", category: "animals" },
  
  // CLOTHES (30)
  { word_de: "die Jacke", forms: { plural: "die Jacken" }, word_en: "jacket", category: "clothes" },
  { word_de: "das Hemd", forms: { plural: "die Hemden" }, word_en: "shirt", category: "clothes" },
  { word_de: "die Hose", forms: { plural: "die Hosen" }, word_en: "pants", category: "clothes" },
  { word_de: "die Schuhe", forms: { plural: "die Schuhe" }, word_en: "shoes", category: "clothes" },
  { word_de: "der Rock", forms: { plural: "die Röcke" }, word_en: "skirt", category: "clothes" },
  { word_de: "das Kleid", forms: { plural: "die Kleider" }, word_en: "dress", category: "clothes" },
  { word_de: "der Pullover", forms: { plural: "die Pullover" }, word_en: "sweater", category: "clothes" },
  { word_de: "der Mantel", forms: { plural: "die Mäntel" }, word_en: "coat", category: "clothes" },
  { word_de: "die Bluse", forms: { plural: "die Blusen" }, word_en: "blouse", category: "clothes" },
  { word_de: "der Anzug", forms: { plural: "die Anzüge" }, word_en: "suit", category: "clothes" },
  { word_de: "die Unterwäsche", forms: { plural: null }, word_en: "underwear", category: "clothes" },
  { word_de: "die Socken", forms: { plural: null }, word_en: "socks", category: "clothes" },
  { word_de: "der Hut", forms: { plural: "die Hüte" }, word_en: "hat", category: "clothes" },
  { word_de: "die Mütze", forms: { plural: "die Mützen" }, word_en: "cap", category: "clothes" },
  { word_de: "der Schal", forms: { plural: "die Schals" }, word_en: "scarf", category: "clothes" },
  { word_de: "die Handschuhe", forms: { plural: null }, word_en: "gloves", category: "clothes" },
  { word_de: "die Stiefel", forms: { plural: null }, word_en: "boots", category: "clothes" },
  { word_de: "die Krawatte", forms: { plural: "die Krawatten" }, word_en: "tie", category: "clothes" },
  { word_de: "die Weste", forms: { plural: "die Westen" }, word_en: "vest", category: "clothes" },
  { word_de: "das T-Shirt", forms: { plural: "die T-Shirts" }, word_en: "t-shirt", category: "clothes" },
  { word_de: "die Jeans", forms: { plural: null }, word_en: "jeans", category: "clothes" },
  { word_de: "die Shorts", forms: { plural: null }, word_en: "shorts", category: "clothes" },
  { word_de: "der Regenmantel", forms: { plural: "die Regenmäntel" }, word_en: "raincoat", category: "clothes" },
  { word_de: "die Badehose", forms: { plural: "die Badehosen" }, word_en: "swim trunks", category: "clothes" },
  { word_de: "der Badeanzug", forms: { plural: "die Badeanzüge" }, word_en: "swimsuit", category: "clothes" },
  { word_de: "die Flip-Flops", forms: { plural: null }, word_en: "flip-flops", category: "clothes" },
  { word_de: "die Sportschuhe", forms: { plural: null }, word_en: "sneakers", category: "clothes" },
  { word_de: "die Hausschuhe", forms: { plural: null }, word_en: "slippers", category: "clothes" },
  { word_de: "die Strumpfhose", forms: { plural: "die Strumpfhosen" }, word_en: "tights", category: "clothes" },
  { word_de: "die Kapuzenjacke", forms: { plural: "die Kapuzenjacken" }, word_en: "hoodie", category: "clothes" }
];
