window.GERMAN_WORDS = [
  // FOOD (50+ words)
  { word_de: "das Brot", forms: { plural: "die Brote" }, word_en: "bread", word_en_plural: "breads", category: "food" },
  { word_de: "der Apfel", forms: { plural: "die Äpfel" }, word_en: "apple", word_en_plural: "apples", category: "food" },
  { word_de: "die Banane", forms: { plural: "die Bananen" }, word_en: "banana", word_en_plural: "bananas", category: "food" },
  { word_de: "die Orange", forms: { plural: "die Orangen" }, word_en: "orange", word_en_plural: "oranges", category: "food" },
  { word_de: "die Erdbeere", forms: { plural: "die Erdbeeren" }, word_en: "strawberry", word_en_plural: "strawberries", category: "food" },
  { word_de: "die Tomate", forms: { plural: "die Tomaten" }, word_en: "tomato", word_en_plural: "tomatoes", category: "food" },
  { word_de: "die Kartoffel", forms: { plural: "die Kartoffeln" }, word_en: "potato", word_en_plural: "potatoes", category: "food" },
  { word_de: "die Karotte", forms: { plural: "die Karotten" }, word_en: "carrot", word_en_plural: "carrots", category: "food" },
  { word_de: "das Fleisch", forms: { plural: null }, word_en: "meat", word_en_plural: "meat", category: "food" },
  { word_de: "der Fisch", forms: { plural: "die Fische" }, word_en: "fish", word_en_plural: "fish", category: "food" },
  { word_de: "die Milch", forms: { plural: null }, word_en: "milk", word_en_plural: "milk", category: "food" },
  { word_de: "der Käse", forms: { plural: "die Käse" }, word_en: "cheese", word_en_plural: "cheeses", category: "food" },
  { word_de: "der Joghurt", forms: { plural: "die Joghurts" }, word_en: "yogurt", word_en_plural: "yogurts", category: "food" },
  { word_de: "die Butter", forms: { plural: null }, word_en: "butter", word_en_plural: "butter", category: "food" },
  { word_de: "das Ei", forms: { plural: "die Eier" }, word_en: "egg", word_en_plural: "eggs", category: "food" },
  { word_de: "der Reis", forms: { plural: null }, word_en: "rice", word_en_plural: "rice", category: "food" },
  { word_de: "die Nudeln", forms: { plural: null }, word_en: "pasta", word_en_plural: "pasta", category: "food" },
  { word_de: "das Salz", forms: { plural: null }, word_en: "salt", word_en_plural: "salt", category: "food" },
  { word_de: "der Zucker", forms: { plural: null }, word_en: "sugar", word_en_plural: "sugar", category: "food" },
  { word_de: "das Wasser", forms: { plural: null }, word_en: "water", word_en_plural: "water", category: "food" },
  { word_de: "der Kaffee", forms: { plural: null }, word_en: "coffee", word_en_plural: "coffee", category: "food" },
  { word_de: "der Tee", forms: { plural: null }, word_en: "tea", word_en_plural: "tea", category: "food" },
  { word_de: "die Suppe", forms: { plural: "die Suppen" }, word_en: "soup", word_en_plural: "soups", category: "food" },
  { word_de: "der Salat", forms: { plural: "die Salate" }, word_en: "salad", word_en_plural: "salads", category: "food" },
  { word_de: "das Gemüse", forms: { plural: null }, word_en: "vegetables", word_en_plural: "vegetables", category: "food" },
  { word_de: "das Obst", forms: { plural: null }, word_en: "fruit", word_en_plural: "fruit", category: "food" },
  { word_de: "die Pizza", forms: { plural: "die Pizzen" }, word_en: "pizza", word_en_plural: "pizzas", category: "food" },
  { word_de: "der Hamburger", forms: { plural: "die Hamburger" }, word_en: "hamburger", word_en_plural: "hamburgers", category: "food" },
  { word_de: "die Wurst", forms: { plural: "die Würste" }, word_en: "sausage", word_en_plural: "sausages", category: "food" },
  { word_de: "das Abendessen", forms: { plural: null }, word_en: "dinner", word_en_plural: "dinners", category: "food" },
  { word_de: "das Frühstück", forms: { plural: null }, word_en: "breakfast", word_en_plural: "breakfasts", category: "food" },
  { word_de: "das Mittagessen", forms: { plural: null }, word_en: "lunch", word_en_plural: "lunches", category: "food" },
  { word_de: "die Zwiebel", forms: { plural: "die Zwiebeln" }, word_en: "onion", word_en_plural: "onions", category: "food" },
  { word_de: "der Pfeffer", forms: { plural: null }, word_en: "pepper", word_en_plural: "pepper", category: "food" },
  { word_de: "das Öl", forms: { plural: "die Öle" }, word_en: "oil", word_en_plural: "oils", category: "food" },
  { word_de: "die Zitrone", forms: { plural: "die Zitronen" }, word_en: "lemon", word_en_plural: "lemons", category: "food" },
  { word_de: "die Traube", forms: { plural: "die Trauben" }, word_en: "grape", word_en_plural: "grapes", category: "food" },
  { word_de: "die Birne", forms: { plural: "die Birnen" }, word_en: "pear", word_en_plural: "pears", category: "food" },
  { word_de: "die Kirsche", forms: { plural: "die Kirschen" }, word_en: "cherry", word_en_plural: "cherries", category: "food" },
  { word_de: "der Pfirsich", forms: { plural: "die Pfirsiche" }, word_en: "peach", word_en_plural: "peaches", category: "food" },
  { word_de: "die Pflaume", forms: { plural: "die Pflaumen" }, word_en: "plum", word_en_plural: "plums", category: "food" },
  { word_de: "die Bohne", forms: { plural: "die Bohnen" }, word_en: "bean", word_en_plural: "beans", category: "food" },
  { word_de: "der Spinat", forms: { plural: null }, word_en: "spinach", word_en_plural: "spinach", category: "food" },
  { word_de: "der Pilz", forms: { plural: "die Pilze" }, word_en: "mushroom", word_en_plural: "mushrooms", category: "food" },
  { word_de: "die Gurke", forms: { plural: "die Gurken" }, word_en: "cucumber", word_en_plural: "cucumbers", category: "food" },
  { word_de: "der Knoblauch", forms: { plural: null }, word_en: "garlic", word_en_plural: "garlic", category: "food" },
  { word_de: "die Sahne", forms: { plural: null }, word_en: "cream", word_en_plural: "cream", category: "food" },
  { word_de: "die Marmelade", forms: { plural: "die Marmeladen" }, word_en: "jam", word_en_plural: "jams", category: "food" },
  { word_de: "der Honig", forms: { plural: null }, word_en: "honey", word_en_plural: "honey", category: "food" },
  { word_de: "der Saft", forms: { plural: "die Säfte" }, word_en: "juice", word_en_plural: "juices", category: "food" },
  { word_de: "die Limonade", forms: { plural: "die Limonaden" }, word_en: "lemonade", word_en_plural: "lemonades", category: "food" },
  { word_de: "die Schokolade", forms: { plural: "die Schokoladen" }, word_en: "chocolate", word_en_plural: "chocolates", category: "food" },
  { word_de: "der Kuchen", forms: { plural: "die Kuchen" }, word_en: "cake", word_en_plural: "cakes", category: "food" },
  { word_de: "das Eis", forms: { plural: null }, word_en: "ice cream", word_en_plural: "ice cream", category: "food" },
  { word_de: "die Pommes frites", forms: { plural: null }, word_en: "french fries", word_en_plural: "french fries", category: "food" },

  // ANIMALS (50+ words)
  { word_de: "der Hund", forms: { plural: "die Hunde" }, word_en: "dog", word_en_plural: "dogs", category: "animals" },
  { word_de: "die Katze", forms: { plural: "die Katzen" }, word_en: "cat", word_en_plural: "cats", category: "animals" },
  { word_de: "der Vogel", forms: { plural: "die Vögel" }, word_en: "bird", word_en_plural: "birds", category: "animals" },
  { word_de: "die Maus", forms: { plural: "die Mäuse" }, word_en: "mouse", word_en_plural: "mice", category: "animals" },
  { word_de: "die Ente", forms: { plural: "die Enten" }, word_en: "duck", word_en_plural: "ducks", category: "animals" },
  { word_de: "das Pferd", forms: { plural: "die Pferde" }, word_en: "horse", word_en_plural: "horses", category: "animals" },
  { word_de: "die Kuh", forms: { plural: "die Kühe" }, word_en: "cow", word_en_plural: "cows", category: "animals" },
  { word_de: "das Schwein", forms: { plural: "die Schweine" }, word_en: "pig", word_en_plural: "pigs", category: "animals" },
  { word_de: "das Schaf", forms: { plural: "die Schafe" }, word_en: "sheep", word_en_plural: "sheep", category: "animals" },
  { word_de: "die Ziege", forms: { plural: "die Ziegen" }, word_en: "goat", word_en_plural: "goats", category: "animals" },
  { word_de: "der Löwe", forms: { plural: "die Löwen" }, word_en: "lion", word_en_plural: "lions", category: "animals" },
  { word_de: "der Tiger", forms: { plural: "die Tiger" }, word_en: "tiger", word_en_plural: "tigers", category: "animals" },
  { word_de: "der Bär", forms: { plural: "die Bären" }, word_en: "bear", word_en_plural: "bears", category: "animals" },
  { word_de: "der Fuchs", forms: { plural: "die Füchse" }, word_en: "fox", word_en_plural: "foxes", category: "animals" },
  { word_de: "der Wolf", forms: { plural: "die Wölfe" }, word_en: "wolf", word_en_plural: "wolves", category: "animals" },
  { word_de: "der Hase", forms: { plural: "die Hasen" }, word_en: "rabbit", word_en_plural: "rabbits", category: "animals" },
  { word_de: "das Kaninchen", forms: { plural: "die Kaninchen" }, word_en: "bunny", word_en_plural: "bunnies", category: "animals" },
  { word_de: "der Affe", forms: { plural: "die Affen" }, word_en: "monkey", word_en_plural: "monkeys", category: "animals" },
  { word_de: "der Elefant", forms: { plural: "die Elefanten" }, word_en: "elephant", word_en_plural: "elephants", category: "animals" },
  { word_de: "die Giraffe", forms: { plural: "die Giraffen" }, word_en: "giraffe", word_en_plural: "giraffes", category: "animals" },
  { word_de: "der Pinguin", forms: { plural: "die Pinguine" }, word_en: "penguin", word_en_plural: "penguins", category: "animals" },
  { word_de: "der Delfin", forms: { plural: "die Delfine" }, word_en: "dolphin", word_en_plural: "dolphins", category: "animals" },
  { word_de: "der Wal", forms: { plural: "die Wale" }, word_en: "whale", word_en_plural: "whales", category: "animals" },
  { word_de: "der Hai", forms: { plural: "die Haie" }, word_en: "shark", word_en_plural: "sharks", category: "animals" },
  { word_de: "die Schlange", forms: { plural: "die Schlangen" }, word_en: "snake", word_en_plural: "snakes", category: "animals" },
  { word_de: "die Schildkröte", forms: { plural: "die Schildkröten" }, word_en: "turtle", word_en_plural: "turtles", category: "animals" },
  { word_de: "die Spinne", forms: { plural: "die Spinnen" }, word_en: "spider", word_en_plural: "spiders", category: "animals" },
  { word_de: "die Biene", forms: { plural: "die Bienen" }, word_en: "bee", word_en_plural: "bees", category: "animals" },
  { word_de: "die Ameise", forms: { plural: "die Ameisen" }, word_en: "ant", word_en_plural: "ants", category: "animals" },
  { word_de: "die Fliege", forms: { plural: "die Fliegen" }, word_en: "fly", word_en_plural: "flies", category: "animals" },
  { word_de: "das Huhn", forms: { plural: "die Hühner" }, word_en: "chicken", word_en_plural: "chickens", category: "animals" },
  { word_de: "der Hahn", forms: { plural: "die Hähne" }, word_en: "rooster", word_en_plural: "roosters", category: "animals" },
  { word_de: "das Küken", forms: { plural: "die Küken" }, word_en: "chick", word_en_plural: "chicks", category: "animals" },
  { word_de: "der Esel", forms: { plural: "die Esel" }, word_en: "donkey", word_en_plural: "donkeys", category: "animals" },
  { word_de: "das Reh", forms: { plural: "die Rehe" }, word_en: "deer", word_en_plural: "deer", category: "animals" },
  { word_de: "der Hirsch", forms: { plural: "die Hirsche" }, word_en: "stag", word_en_plural: "stags", category: "animals" },
  { word_de: "das Eichhörnchen", forms: { plural: "die Eichhörnchen" }, word_en: "squirrel", word_en_plural: "squirrels", category: "animals" },
  { word_de: "der Igel", forms: { plural: "die Igel" }, word_en: "hedgehog", word_en_plural: "hedgehogs", category: "animals" },
  { word_de: "der Maulwurf", forms: { plural: "die Maulwürfe" }, word_en: "mole", word_en_plural: "moles", category: "animals" },
  { word_de: "der Frosch", forms: { plural: "die Frösche" }, word_en: "frog", word_en_plural: "frogs", category: "animals" },
  { word_de: "die Kröte", forms: { plural: "die Kröten" }, word_en: "toad", word_en_plural: "toads", category: "animals" },
  { word_de: "der Schmetterling", forms: { plural: "die Schmetterlinge" }, word_en: "butterfly", word_en_plural: "butterflies", category: "animals" },
  { word_de: "die Motte", forms: { plural: "die Motten" }, word_en: "moth", word_en_plural: "moths", category: "animals" },
  { word_de: "die Libelle", forms: { plural: "die Libellen" }, word_en: "dragonfly", word_en_plural: "dragonflies", category: "animals" },
  { word_de: "die Schnecke", forms: { plural: "die Schnecken" }, word_en: "snail", word_en_plural: "snails", category: "animals" },
  { word_de: "der Wurm", forms: { plural: "die Würmer" }, word_en: "worm", word_en_plural: "worms", category: "animals" },
  { word_de: "die Qualle", forms: { plural: "die Quallen" }, word_en: "jellyfish", word_en_plural: "jellyfish", category: "animals" },
  { word_de: "der Krebs", forms: { plural: "die Krebse" }, word_en: "crab", word_en_plural: "crabs", category: "animals" },
  { word_de: "der Tintenfisch", forms: { plural: "die Tintenfische" }, word_en: "octopus", word_en_plural: "octopuses", category: "animals" },
  { word_de: "das Krokodil", forms: { plural: "die Krokodile" }, word_en: "crocodile", word_en_plural: "crocodiles", category: "animals" },
  { word_de: "die Eidechse", forms: { plural: "die Eidechsen" }, word_en: "lizard", word_en_plural: "lizards", category: "animals" },
  { word_de: "das Känguru", forms: { plural: "die Kängurus" }, word_en: "kangaroo", word_en_plural: "kangaroos", category: "animals" },
  { word_de: "das Kameel", forms: { plural: "die Kameele" }, word_en: "camel", word_en_plural: "camels", category: "animals" },
  { word_de: "der Panda", forms: { plural: "die Pandas" }, word_en: "panda", word_en_plural: "pandas", category: "animals" },

  // CLOTHES (50+ words)
  { word_de: "die Jacke", forms: { plural: "die Jacken" }, word_en: "jacket", word_en_plural: "jackets", category: "clothes" },
  { word_de: "das Hemd", forms: { plural: "die Hemden" }, word_en: "shirt", word_en_plural: "shirts", category: "clothes" },
  { word_de: "die Hose", forms: { plural: "die Hosen" }, word_en: "pants", word_en_plural: "pants", category: "clothes" },
  { word_de: "die Schuhe", forms: { plural: "die Schuhe" }, word_en: "shoes", word_en_plural: "shoes", category: "clothes" },
  { word_de: "der Rock", forms: { plural: "die Röcke" }, word_en: "skirt", word_en_plural: "skirts", category: "clothes" },
  { word_de: "das Kleid", forms: { plural: "die Kleider" }, word_en: "dress", word_en_plural: "dresses", category: "clothes" },
  { word_de: "der Pullover", forms: { plural: "die Pullover" }, word_en: "sweater", word_en_plural: "sweaters", category: "clothes" },
  { word_de: "der Mantel", forms: { plural: "die Mäntel" }, word_en: "coat", word_en_plural: "coats", category: "clothes" },
  { word_de: "die Bluse", forms: { plural: "die Blusen" }, word_en: "blouse", word_en_plural: "blouses", category: "clothes" },
  { word_de: "der Anzug", forms: { plural: "die Anzüge" }, word_en: "suit", word_en_plural: "suits", category: "clothes" },
  { word_de: "die Unterwäsche", forms: { plural: null }, word_en: "underwear", word_en_plural: "underwear", category: "clothes" },
  { word_de: "die Socken", forms: { plural: null }, word_en: "socks", word_en_plural: "socks", category: "clothes" },
  { word_de: "der Hut", forms: { plural: "die Hüte" }, word_en: "hat", word_en_plural: "hats", category: "clothes" },
  { word_de: "die Mütze", forms: { plural: "die Mützen" }, word_en: "cap", word_en_plural: "caps", category: "clothes" },
  { word_de: "der Schal", forms: { plural: "die Schals" }, word_en: "scarf", word_en_plural: "scarves", category: "clothes" },
  { word_de: "die Handschuhe", forms: { plural: null }, word_en: "gloves", word_en_plural: "gloves", category: "clothes" },
  { word_de: "die Stiefel", forms: { plural: null }, word_en: "boots", word_en_plural: "boots", category: "clothes" },
  { word_de: "die Krawatte", forms: { plural: "die Krawatten" }, word_en: "tie", word_en_plural: "ties", category: "clothes" },
  { word_de: "die Weste", forms: { plural: "die Westen" }, word_en: "vest", word_en_plural: "vests", category: "clothes" },
  { word_de: "das T-Shirt", forms: { plural: "die T-Shirts" }, word_en: "t-shirt", word_en_plural: "t-shirts", category: "clothes" },
  { word_de: "die Jeans", forms: { plural: null }, word_en: "jeans", word_en_plural: "jeans", category: "clothes" },
  { word_de: "die Shorts", forms: { plural: null }, word_en: "shorts", word_en_plural: "shorts", category: "clothes" },
  { word_de: "der Regenmantel", forms: { plural: "die Regenmäntel" }, word_en: "raincoat", word_en_plural: "raincoats", category: "clothes" },
  { word_de: "die Badehose", forms: { plural: "die Badehosen" }, word_en: "swim trunks", word_en_plural: "swim trunks", category: "clothes" },
  { word_de: "der Badeanzug", forms: { plural: "die Badeanzüge" }, word_en: "swimsuit", word_en_plural: "swimsuits", category: "clothes" },
  { word_de: "die Flip-Flops", forms: { plural: null }, word_en: "flip-flops", word_en_plural: "flip-flops", category: "clothes" },
  { word_de: "die Sportschuhe", forms: { plural: null }, word_en: "sneakers", word_en_plural: "sneakers", category: "clothes" },
  { word_de: "die Hausschuhe", forms: { plural: null }, word_en: "slippers", word_en_plural: "slippers", category: "clothes" },
  { word_de: "die Strumpfhose", forms: { plural: "die Strumpfhosen" }, word_en: "tights", word_en_plural: "tights", category: "clothes" },
  { word_de: "die Kapuzenjacke", forms: { plural: "die Kapuzenjacken" }, word_en: "hoodie", word_en_plural: "hoodies", category: "clothes" },
  { word_de: "die Unterhose", forms: { plural: "die Unterhosen" }, word_en: "underpants", word_en_plural: "underpants", category: "clothes" },
  { word_de: "der Schlafanzug", forms: { plural: "die Schlafanzüge" }, word_en: "pajamas", word_en_plural: "pajamas", category: "clothes" },
  { word_de: "die Pyjama", forms: { plural: "die Pyjamas" }, word_en: "pyjamas", word_en_plural: "pyjamas", category: "clothes" },
  { word_de: "der Gürtel", forms: { plural: "die Gürtel" }, word_en: "belt", word_en_plural: "belts", category: "clothes" },
  { word_de: "die Sonnenbrille", forms: { plural: "die Sonnenbrillen" }, word_en: "sunglasses", word_en_plural: "sunglasses", category: "clothes" },
  { word_de: "die Brille", forms: { plural: "die Brillen" }, word_en: "glasses", word_en_plural: "glasses", category: "clothes" },
  { word_de: "die Ohrringe", forms: { plural: null }, word_en: "earrings", word_en_plural: "earrings", category: "clothes" },
  { word_de: "die Halskette", forms: { plural: "die Halsketten" }, word_en: "necklace", word_en_plural: "necklaces", category: "clothes" },
  { word_de: "der Ring", forms: { plural: "die Ringe" }, word_en: "ring", word_en_plural: "rings", category: "clothes" },
  { word_de: "die Armbanduhr", forms: { plural: "die Armbanduhren" }, word_en: "wristwatch", word_en_plural: "wristwatches", category: "clothes" },
  { word_de: "das Armband", forms: { plural: "die Armbänder" }, word_en: "bracelet", word_en_plural: "bracelets", category: "clothes" },
  { word_de: "die Tasche", forms: { plural: "die Taschen" }, word_en: "bag", word_en_plural: "bags", category: "clothes" },
  { word_de: "der Rucksack", forms: { plural: "die Rucksäcke" }, word_en: "backpack", word_en_plural: "backpacks", category: "clothes" },
  { word_de: "die Handtasche", forms: { plural: "die Handtaschen" }, word_en: "handbag", word_en_plural: "handbags", category: "clothes" },
  { word_de: "der Regenschirm", forms: { plural: "die Regenschirme" }, word_en: "umbrella", word_en_plural: "umbrellas", category: "clothes" },
  { word_de: "die Badekappe", forms: { plural: "die Badekappen" }, word_en: "swimming cap", word_en_plural: "swimming caps", category: "clothes" },
  { word_de: "die Badeschuhe", forms: { plural: null }, word_en: "water shoes", word_en_plural: "water shoes", category: "clothes" },
  { word_de: "die Leggings", forms: { plural: null }, word_en: "leggings", word_en_plural: "leggings", category: "clothes" },
  { word_de: "der Overall", forms: { plural: "die Overalls" }, word_en: "overall", word_en_plural: "overalls", category: "clothes" },
  { word_de: "der Trainingsanzug", forms: { plural: "die Trainingsanzüge" }, word_en: "tracksuit", word_en_plural: "tracksuits", category: "clothes" },

  // FAMILY (50+ words)
  { word_de: "die Familie", forms: { plural: "die Familien" }, word_en: "family", word_en_plural: "families", category: "family" },
  { word_de: "die Mutter", forms: { plural: "die Mütter" }, word_en: "mother", word_en_plural: "mothers", category: "family" },
  { word_de: "der Vater", forms: { plural: "die Väter" }, word_en: "father", word_en_plural: "fathers", category: "family" },
  { word_de: "die Schwester", forms: { plural: "die Schwestern" }, word_en: "sister", word_en_plural: "sisters", category: "family" },
  { word_de: "der Bruder", forms: { plural: "die Brüder" }, word_en: "brother", word_en_plural: "brothers", category: "family" },
  { word_de: "der Sohn", forms: { plural: "die Söhne" }, word_en: "son", word_en_plural: "sons", category: "family" },
  { word_de: "die Tochter", forms: { plural: "die Töchter" }, word_en: "daughter", word_en_plural: "daughters", category: "family" },
  { word_de: "die Oma", forms: { plural: "die Omas" }, word_en: "grandmother", word_en_plural: "grandmothers", category: "family" },
  { word_de: "der Opa", forms: { plural: "die Opas" }, word_en: "grandfather", word_en_plural: "grandfathers", category: "family" },
  { word_de: "die Tante", forms: { plural: "die Tanten" }, word_en: "aunt", word_en_plural: "aunts", category: "family" },
  { word_de: "der Onkel", forms: { plural: "die Onkel" }, word_en: "uncle", word_en_plural: "uncles", category: "family" },
  { word_de: "der Cousin", forms: { plural: "die Cousins" }, word_en: "cousin (male)", word_en_plural: "cousins (male)", category: "family" },
  { word_de: "die Cousine", forms: { plural: "die Cousinen" }, word_en: "cousin (female)", word_en_plural: "cousins (female)", category: "family" },
  { word_de: "die Großmutter", forms: { plural: "die Großmütter" }, word_en: "grandmother", word_en_plural: "grandmothers", category: "family" },
  { word_de: "der Großvater", forms: { plural: "die Großväter" }, word_en: "grandfather", word_en_plural: "grandfathers", category: "family" },
  { word_de: "die Enkelin", forms: { plural: "die Enkelinnen" }, word_en: "granddaughter", word_en_plural: "granddaughters", category: "family" },
  { word_de: "der Enkel", forms: { plural: "die Enkel" }, word_en: "grandson", word_en_plural: "grandsons", category: "family" },
  { word_de: "die Nichte", forms: { plural: "die Nichten" }, word_en: "niece", word_en_plural: "nieces", category: "family" },
  { word_de: "der Neffe", forms: { plural: "die Neffen" }, word_en: "nephew", word_en_plural: "nephews", category: "family" },
  { word_de: "die Schwiegermutter", forms: { plural: "die Schwiegermütter" }, word_en: "mother-in-law", word_en_plural: "mothers-in-law", category: "family" },
  { word_de: "der Schwiegervater", forms: { plural: "die Schwiegerväter" }, word_en: "father-in-law", word_en_plural: "fathers-in-law", category: "family" },
  { word_de: "die Schwägerin", forms: { plural: "die Schwägerinnen" }, word_en: "sister-in-law", word_en_plural: "sisters-in-law", category: "family" },
  { word_de: "der Schwager", forms: { plural: "die Schwager" }, word_en: "brother-in-law", word_en_plural: "brothers-in-law", category: "family" },
  { word_de: "die Stiefmutter", forms: { plural: "die Stiefmütter" }, word_en: "stepmother", word_en_plural: "stepmothers", category: "family" },
  { word_de: "der Stiefvater", forms: { plural: "die Stiefväter" }, word_en: "stepfather", word_en_plural},
    
  // HOUSE/ROOMS
  { word_de: "das Haus", forms: { plural: "die Häuser" }, word_en: "house", word_en_plural: "houses", category: "house" },
  { word_de: "die Wohnung", forms: { plural: "die Wohnungen" }, word_en: "apartment", word_en_plural: "apartments", category: "house" },
  { word_de: "das Zimmer", forms: { plural: "die Zimmer" }, word_en: "room", word_en_plural: "rooms", category: "house" },
  { word_de: "die Küche", forms: { plural: "die Küchen" }, word_en: "kitchen", word_en_plural: "kitchens", category: "house" },
  { word_de: "das Badezimmer", forms: { plural: "die Badezimmer" }, word_en: "bathroom", word_en_plural: "bathrooms", category: "house" },
  { word_de: "das Schlafzimmer", forms: { plural: "die Schlafzimmer" }, word_en: "bedroom", word_en_plural: "bedrooms", category: "house" },
  { word_de: "das Wohnzimmer", forms: { plural: "die Wohnzimmer" }, word_en: "living room", word_en_plural: "living rooms", category: "house" },
  { word_de: "die Tür", forms: { plural: "die Türen" }, word_en: "door", word_en_plural: "doors", category: "house" },
  { word_de: "das Fenster", forms: { plural: "die Fenster" }, word_en: "window", word_en_plural: "windows", category: "house" },
  { word_de: "der Tisch", forms: { plural: "die Tische" }, word_en: "table", word_en_plural: "tables", category: "house" },
  { word_de: "der Stuhl", forms: { plural: "die Stühle" }, word_en: "chair", word_en_plural: "chairs", category: "house" },
  { word_de: "das Bett", forms: { plural: "die Betten" }, word_en: "bed", word_en_plural: "beds", category: "house" },
  { word_de: "der Schrank", forms: { plural: "die Schränke" }, word_en: "wardrobe", word_en_plural: "wardrobes", category: "house" },
  { word_de: "das Sofa", forms: { plural: "die Sofas" }, word_en: "sofa", word_en_plural: "sofas", category: "house" },
  { word_de: "der Spiegel", forms: { plural: "die Spiegel" }, word_en: "mirror", word_en_plural: "mirrors", category: "house" },
  { word_de: "die Lampe", forms: { plural: "die Lampen" }, word_en: "lamp", word_en_plural: "lamps", category: "house" },
  
  // CITY/PLACES
  { word_de: "die Stadt", forms: { plural: "die Städte" }, word_en: "city", word_en_plural: "cities", category: "city" },
  { word_de: "das Dorf", forms: { plural: "die Dörfer" }, word_en: "village", word_en_plural: "villages", category: "city" },
  { word_de: "die Straße", forms: { plural: "die Straßen" }, word_en: "street", word_en_plural: "streets", category: "city" },
  { word_de: "der Platz", forms: { plural: "die Plätze" }, word_en: "square", word_en_plural: "squares", category: "city" },
  { word_de: "der Park", forms: { plural: "die Parks" }, word_en: "park", word_en_plural: "parks", category: "city" },
  { word_de: "die Schule", forms: { plural: "die Schulen" }, word_en: "school", word_en_plural: "schools", category: "city" },
  { word_de: "das Krankenhaus", forms: { plural: "die Krankenhäuser" }, word_en: "hospital", word_en_plural: "hospitals", category: "city" },
  { word_de: "die Bank", forms: { plural: "die Banken" }, word_en: "bank", word_en_plural: "banks", category: "city" },
  { word_de: "das Restaurant", forms: { plural: "die Restaurants" }, word_en: "restaurant", word_en_plural: "restaurants", category: "city" },
  { word_de: "das Café", forms: { plural: "die Cafés" }, word_en: "café", word_en_plural: "cafés", category: "city" },
  { word_de: "der Supermarkt", forms: { plural: "die Supermärkte" }, word_en: "supermarket", word_en_plural: "supermarkets", category: "city" },
  { word_de: "die Apotheke", forms: { plural: "die Apotheken" }, word_en: "pharmacy", word_en_plural: "pharmacies", category: "city" },
  { word_de: "der Bahnhof", forms: { plural: "die Bahnhöfe" }, word_en: "train station", word_en_plural: "train stations", category: "city" },
  { word_de: "die Bushaltestelle", forms: { plural: "die Bushaltestellen" }, word_en: "bus stop", word_en_plural: "bus stops", category: "city" },
  { word_de: "das Kino", forms: { plural: "die Kinos" }, word_en: "cinema", word_en_plural: "cinemas", category: "city" },
  { word_de: "das Theater", forms: { plural: "die Theater" }, word_en: "theater", word_en_plural: "theaters", category: "city" },
  { word_de: "die Bibliothek", forms: { plural: "die Bibliotheken" }, word_en: "library", word_en_plural: "libraries", category: "city" },
  
  // PROFESSIONS
  { word_de: "der Lehrer", forms: { plural: "die Lehrer" }, word_en: "teacher (male)", word_en_plural: "teachers (male)", category: "professions" },
  { word_de: "die Lehrerin", forms: { plural: "die Lehrerinnen" }, word_en: "teacher (female)", word_en_plural: "teachers (female)", category: "professions" },
  { word_de: "der Arzt", forms: { plural: "die Ärzte" }, word_en: "doctor (male)", word_en_plural: "doctors (male)", category: "professions" },
  { word_de: "die Ärztin", forms: { plural: "die Ärztinnen" }, word_en: "doctor (female)", word_en_plural: "doctors (female)", category: "professions" },
  { word_de: "der Polizist", forms: { plural: "die Polizisten" }, word_en: "policeman", word_en_plural: "policemen", category: "professions" },
  { word_de: "die Polizistin", forms: { plural: "die Polizistinnen" }, word_en: "policewoman", word_en_plural: "policewomen", category: "professions" },
  { word_de: "der Koch", forms: { plural: "die Köche" }, word_en: "cook (male)", word_en_plural: "cooks (male)", category: "professions" },
  { word_de: "die Köchin", forms: { plural: "die Köchinnen" }, word_en: "cook (female)", word_en_plural: "cooks (female)", category: "professions" },
  { word_de: "der Ingenieur", forms: { plural: "die Ingenieure" }, word_en: "engineer (male)", word_en_plural: "engineers (male)", category: "professions" },
  { word_de: "die Ingenieurin", forms: { plural: "die Ingenieurinnen" }, word_en: "engineer (female)", word_en_plural: "engineers (female)", category: "professions" },
  { word_de: "der Student", forms: { plural: "die Studenten" }, word_en: "student (male)", word_en_plural: "students (male)", category: "professions" },
  { word_de: "die Studentin", forms: { plural: "die Studentinnen" }, word_en: "student (female)", word_en_plural: "students (female)", category: "professions" },
  { word_de: "der Fahrer", forms: { plural: "die Fahrer" }, word_en: "driver (male)", word_en_plural: "drivers (male)", category: "professions" },
  { word_de: "die Fahrerin", forms: { plural: "die Fahrerinnen" }, word_en: "driver (female)", word_en_plural: "drivers (female)", category: "professions" },
  { word_de: "der Verkäufer", forms: { plural: "die Verkäufer" }, word_en: "salesperson (male)", word_en_plural: "salespeople (male)", category: "professions" },
  { word_de: "die Verkäuferin", forms: { plural: "die Verkäuferinnen" }, word_en: "salesperson (female)", word_en_plural: "salespeople (female)", category: "professions" },
  
  // TIME
  { word_de: "die Zeit", forms: { plural: "die Zeiten" }, word_en: "time", word_en_plural: "times", category: "time" },
  { word_de: "die Stunde", forms: { plural: "die Stunden" }, word_en: "hour", word_en_plural: "hours", category: "time" },
  { word_de: "die Minute", forms: { plural: "die Minuten" }, word_en: "minute", word_en_plural: "minutes", category: "time" },
  { word_de: "die Sekunde", forms: { plural: "die Sekunden" }, word_en: "second", word_en_plural: "seconds", category: "time" },
  { word_de: "der Tag", forms: { plural: "die Tage" }, word_en: "day", word_en_plural: "days", category: "time" },
  { word_de: "die Nacht", forms: { plural: "die Nächte" }, word_en: "night", word_en_plural: "nights", category: "time" },
  { word_de: "die Woche", forms: { plural: "die Wochen" }, word_en: "week", word_en_plural: "weeks", category: "time" },
  { word_de: "der Monat", forms: { plural: "die Monate" }, word_en: "month", word_en_plural: "months", category: "time" },
  { word_de: "das Jahr", forms: { plural: "die Jahre" }, word_en: "year", word_en_plural: "years", category: "time" },
  { word_de: "der Morgen", forms: { plural: "die Morgen" }, word_en: "morning", word_en_plural: "mornings", category: "time" },
  { word_de: "der Nachmittag", forms: { plural: "die Nachmittage" }, word_en: "afternoon", word_en_plural: "afternoons", category: "time" },
  { word_de: "der Abend", forms: { plural: "die Abende" }, word_en: "evening", word_en_plural: "evenings", category: "time" },
  { word_de: "die Uhr", forms: { plural: "die Uhren" }, word_en: "clock/watch", word_en_plural: "clocks/watches", category: "time" },
  
  // NUMBERS (1-20)
  { word_de: "eins", forms: { plural: null }, word_en: "one", word_en_plural: "ones", category: "numbers" },
  { word_de: "zwei", forms: { plural: null }, word_en: "two", word_en_plural: "twos", category: "numbers" },
  { word_de: "drei", forms: { plural: null }, word_en: "three", word_en_plural: "threes", category: "numbers" },
  { word_de: "vier", forms: { plural: null }, word_en: "four", word_en_plural: "fours", category: "numbers" },
  { word_de: "fünf", forms: { plural: null }, word_en: "five", word_en_plural: "fives", category: "numbers" },
  { word_de: "sechs", forms: { plural: null }, word_en: "six", word_en_plural: "sixes", category: "numbers" },
  { word_de: "sieben", forms: { plural: null }, word_en: "seven", word_en_plural: "sevens", category: "numbers" },
  { word_de: "acht", forms: { plural: null }, word_en: "eight", word_en_plural: "eights", category: "numbers" },
  { word_de: "neun", forms: { plural: null }, word_en: "nine", word_en_plural: "nines", category: "numbers" },
  { word_de: "zehn", forms: { plural: null }, word_en: "ten", word_en_plural: "tens", category: "numbers" },
  { word_de: "elf", forms: { plural: null }, word_en: "eleven", word_en_plural: "elevens", category: "numbers" },
  { word_de: "zwölf", forms: { plural: null }, word_en: "twelve", word_en_plural: "twelves", category: "numbers" },
  { word_de: "dreizehn", forms: { plural: null }, word_en: "thirteen", word_en_plural: "thirteens", category: "numbers" },
  { word_de: "vierzehn", forms: { plural: null }, word_en: "fourteen", word_en_plural: "fourteens", category: "numbers" },
  { word_de: "fünfzehn", forms: { plural: null }, word_en: "fifteen", word_en_plural: "fifteens", category: "numbers" },
  { word_de: "sechzehn", forms: { plural: null }, word_en: "sixteen", word_en_plural: "sixteens", category: "numbers" },
  { word_de: "siebzehn", forms: { plural: null }, word_en: "seventeen", word_en_plural: "seventeens", category: "numbers" },
  { word_de: "achtzehn", forms: { plural: null }, word_en: "eighteen", word_en_plural: "eighteens", category: "numbers" },
  { word_de: "neunzehn", forms: { plural: null }, word_en: "nineteen", word_en_plural: "nineteens", category: "numbers" },
  { word_de: "zwanzig", forms: { plural: null }, word_en: "twenty", word_en_plural: "twenties", category: "numbers" },
  
  // COLORS
  { word_de: "rot", forms: { plural: null }, word_en: "red", word_en_plural: "reds", category: "colors" },
  { word_de: "blau", forms: { plural: null }, word_en: "blue", word_en_plural: "blues", category: "colors" },
  { word_de: "grün", forms: { plural: null }, word_en: "green", word_en_plural: "greens", category: "colors" },
  { word_de: "gelb", forms: { plural: null }, word_en: "yellow", word_en_plural: "yellows", category: "colors" },
  { word_de: "schwarz", forms: { plural: null }, word_en: "black", word_en_plural: "blacks", category: "colors" },
  { word_de: "weiß", forms: { plural: null }, word_en: "white", word_en_plural: "whites", category: "colors" },
  { word_de: "braun", forms: { plural: null }, word_en: "brown", word_en_plural: "browns", category: "colors" },
  { word_de: "grau", forms: { plural: null }, word_en: "gray", word_en_plural: "grays", category: "colors" },
  { word_de: "orange", forms: { plural: null }, word_en: "orange", word_en_plural: "oranges", category: "colors" },
  { word_de: "lila", forms: { plural: null }, word_en: "purple", word_en_plural: "purples", category: "colors" },
  { word_de: "rosa", forms: { plural: null }, word_en: "pink", word_en_plural: "pinks", category: "colors" },
  
  // TRANSPORTATION
  { word_de: "das Auto", forms: { plural: "die Autos" }, word_en: "car", word_en_plural: "cars", category: "transportation" },
  { word_de: "der Bus", forms: { plural: "die Busse" }, word_en: "bus", word_en_plural: "buses", category: "transportation" },
  { word_de: "der Zug", forms: { plural: "die Züge" }, word_en: "train", word_en_plural: "trains", category: "transportation" },
  { word_de: "das Fahrrad", forms: { plural: "die Fahrräder" }, word_en: "bicycle", word_en_plural: "bicycles", category: "transportation" },
  { word_de: "das Motorrad", forms: { plural: "die Motorräder" }, word_en: "motorcycle", word_en_plural: "motorcycles", category: "transportation" },
  { word_de: "das Flugzeug", forms: { plural: "die Flugzeuge" }, word_en: "airplane", word_en_plural: "airplanes", category: "transportation" },
  { word_de: "das Schiff", forms: { plural: "die Schiffe" }, word_en: "ship", word_en_plural: "ships", category: "transportation" },
  { word_de: "die U-Bahn", forms: { plural: "die U-Bahnen" }, word_en: "subway", word_en_plural: "subways", category: "transportation" },
  { word_de: "die Straßenbahn", forms: { plural: "die Straßenbahnen" }, word_en: "tram", word_en_plural: "trams", category: "transportation" },
  { word_de: "das Taxi", forms: { plural: "die Taxis" }, word_en: "taxi", word_en_plural: "taxis", category: "transportation" },
  
  // BODY PARTS
  { word_de: "der Kopf", forms: { plural: "die Köpfe" }, word_en: "head", word_en_plural: "heads", category: "body" },
  { word_de: "das Auge", forms: { plural: "die Augen" }, word_en: "eye", word_en_plural: "eyes", category: "body" },
  { word_de: "die Nase", forms: { plural: "die Nasen" }, word_en: "nose", word_en_plural: "noses", category: "body" },
  { word_de: "der Mund", forms: { plural: "die Münder" }, word_en: "mouth", word_en_plural: "mouths", category: "body" },
  { word_de: "das Ohr", forms: { plural: "die Ohren" }, word_en: "ear", word_en_plural: "ears", category: "body" },
  { word_de: "der Arm", forms: { plural: "die Arme" }, word_en: "arm", word_en_plural: "arms", category: "body" },
  { word_de: "die Hand", forms: { plural: "die Hände" }, word_en: "hand", word_en_plural: "hands", category: "body" },
  { word_de: "das Bein", forms: { plural: "die Beine" }, word_en: "leg", word_en_plural: "legs", category: "body" },
  { word_de: "der Fuß", forms: { plural: "die Füße" }, word_en: "foot", word_en_plural: "feet", category: "body" },
  { word_de: "das Herz", forms: { plural: "die Herzen" }, word_en: "heart", word_en_plural: "hearts", category: "body" },
  { word_de: "der Rücken", forms: { plural: "die Rücken" }, word_en: "back", word_en_plural: "backs", category: "body" },
  { word_de: "der Bauch", forms: { plural: "die Bäuche" }, word_en: "stomach", word_en_plural: "stomachs", category: "body" },
  
  // WEATHER/SEASONS
  { word_de: "das Wetter", forms: { plural: null }, word_en: "weather", word_en_plural: "weather", category: "weather" },
  { word_de: "die Sonne", forms: { plural: "die Sonnen" }, word_en: "sun", word_en_plural: "suns", category: "weather" },
  { word_de: "der Regen", forms: { plural: null }, word_en: "rain", word_en_plural: "rain", category: "weather" },
  { word_de: "der Schnee", forms: { plural: null }, word_en: "snow", word_en_plural: "snow", category: "weather" },
  { word_de: "der Wind", forms: { plural: "die Winde" }, word_en: "wind", word_en_plural: "winds", category: "weather" },
  { word_de: "die Wolke", forms: { plural: "die Wolken" }, word_en: "cloud", word_en_plural: "clouds", category: "weather" },
  { word_de: "der Frühling", forms: { plural: "die Frühlinge" }, word_en: "spring", word_en_plural: "springs", category: "weather" },
  { word_de: "der Sommer", forms: { plural: "die Sommer" }, word_en: "summer", word_en_plural: "summers", category: "weather" },
  { word_de: "der Herbst", forms: { plural: "die Herbste" }, word_en: "autumn", word_en_plural: "autumns", category: "weather" },
  { word_de: "der Winter", forms: { plural: "die Winter" }, word_en: "winter", word_en_plural: "winters", category: "weather" },
  
  // SCHOOL/STUDY
  { word_de: "das Buch", forms: { plural: "die Bücher" }, word_en: "book", word_en_plural: "books", category: "school" },
  { word_de: "der Stift", forms: { plural: "die Stifte" }, word_en: "pen", word_en_plural: "pens", category: "school" },
  { word_de: "der Bleistift", forms: { plural: "die Bleistifte" }, word_en: "pencil", word_en_plural: "pencils", category: "school" },
  { word_de: "das Heft", forms: { plural: "die Hefte" }, word_en: "notebook", word_en_plural: "notebooks", category: "school" },
  { word_de: "der Radiergummi", forms: { plural: "die Radiergummis" }, word_en: "eraser", word_en_plural: "erasers", category: "school" },
  { word_de: "der Rucksack", forms: { plural: "die Rucksäcke" }, word_en: "backpack", word_en_plural: "backpacks", category: "school" },
  { word_de: "die Tafel", forms: { plural: "die Tafeln" }, word_en: "blackboard", word_en_plural: "blackboards", category: "school" },
  { word_de: "der Computer", forms: { plural: "die Computer" }, word_en: "computer", word_en_plural: "computers", category: "school" },
  
  // DAILY ACTIVITIES (verbs - keeping plural same as singular)
  { word_de: "essen", forms: { plural: null }, word_en: "to eat", word_en_plural: "to eat", category: "verbs" },
  { word_de: "trinken", forms: { plural: null }, word_en: "to drink", word_en_plural: "to drink", category: "verbs" },
  { word_de: "schlafen", forms: { plural: null }, word_en: "to sleep", word_en_plural: "to sleep", category: "verbs" },
  { word_de: "lesen", forms: { plural: null }, word_en: "to read", word_en_plural: "to read", category: "verbs" },
  { word_de: "schreiben", forms: { plural: null }, word_en: "to write", word_en_plural: "to write", category: "verbs" },
  { word_de: "sprechen", forms: { plural: null }, word_en: "to speak", word_en_plural: "to speak", category: "verbs" },
  { word_de: "hören", forms: { plural: null }, word_en: "to hear", word_en_plural: "to hear", category: "verbs" },
  { word_de: "sehen", forms: { plural: null }, word_en: "to see", word_en_plural: "to see", category: "verbs" },
  { word_de: "gehen", forms: { plural: null }, word_en: "to go", word_en_plural: "to go", category: "verbs" },
  { word_de: "kommen", forms: { plural: null }, word_en: "to come", word_en_plural: "to come", category: "verbs" },
  { word_de: "arbeiten", forms: { plural: null }, word_en: "to work", word_en_plural: "to work", category: "verbs" },
  { word_de: "lernen", forms: { plural: null }, word_en: "to learn", word_en_plural: "to learn", category: "verbs" },
  { word_de: "spielen", forms: { plural: null }, word_en: "to play", word_en_plural: "to play", category: "verbs" },
  { word_de: "kaufen", forms: { plural: null }, word_en: "to buy", word_en_plural: "to buy", category: "verbs" },
  { word_de: "verkaufen", forms: { plural: null }, word_en: "to sell", word_en_plural: "to sell", category: "verbs" },
  
  // ADJECTIVES (basic - keeping plural same as singular)
  { word_de: "groß", forms: { plural: null }, word_en: "big", word_en_plural: "big", category: "adjectives" },
  { word_de: "klein", forms: { plural: null }, word_en: "small", word_en_plural: "small", category: "adjectives" },
  { word_de: "gut", forms: { plural: null }, word_en: "good", word_en_plural: "good", category: "adjectives" },
  { word_de: "schlecht", forms: { plural: null }, word_en: "bad", word_en_plural: "bad", category: "adjectives" },
  { word_de: "schön", forms: { plural: null }, word_en: "beautiful", word_en_plural: "beautiful", category: "adjectives" },
  { word_de: "hässlich", forms: { plural: null }, word_en: "ugly", word_en_plural: "ugly", category: "adjectives" },
  { word_de: "alt", forms: { plural: null }, word_en: "old", word_en_plural: "old", category: "adjectives" },
  { word_de: "jung", forms: { plural: null }, word_en: "young", word_en_plural: "young", category: "adjectives" },
  { word_de: "neu", forms: { plural: null }, word_en: "new", word_en_plural: "new", category: "adjectives" },
  { word_de: "teuer", forms: { plural: null }, word_en: "expensive", word_en_plural: "expensive", category: "adjectives" },
  { word_de: "billig", forms: { plural: null }, word_en: "cheap", word_en_plural: "cheap", category: "adjectives" },
  { word_de: "schnell", forms: { plural: null }, word_en: "fast", word_en_plural: "fast", category: "adjectives" },
  { word_de: "langsam", forms: { plural: null }, word_en: "slow", word_en_plural: "slow", category: "adjectives" },
  { word_de: "leicht", forms: { plural: null }, word_en: "easy/light", word_en_plural: "easy/light", category: "adjectives" },
  { word_de: "schwer", forms: { plural: null }, word_en: "heavy/difficult", word_en_plural: "heavy/difficult", category: "adjectives" },
  
  // PREPOSITIONS/DIRECTIONS (keeping plural same as singular)
  { word_de: "in", forms: { plural: null }, word_en: "in", word_en_plural: "in", category: "prepositions" },
  { word_de: "auf", forms: { plural: null }, word_en: "on", word_en_plural: "on", category: "prepositions" },
  { word_de: "unter", forms: { plural: null }, word_en: "under", word_en_plural: "under", category: "prepositions" },
  { word_de: "neben", forms: { plural: null }, word_en: "next to", word_en_plural: "next to", category: "prepositions" },
  { word_de: "zwischen", forms: { plural: null }, word_en: "between", word_en_plural: "between", category: "prepositions" },
  { word_de: "hinter", forms: { plural: null }, word_en: "behind", word_en_plural: "behind", category: "prepositions" },
  { word_de: "vor", forms: { plural: null }, word_en: "in front of", word_en_plural: "in front of", category: "prepositions" },
  { word_de: "links", forms: { plural: null }, word_en: "left", word_en_plural: "left", category: "directions" },
  { word_de: "rechts", forms: { plural: null }, word_en: "right", word_en_plural: "right", category: "directions" },
  { word_de: "geradeaus", forms: { plural: null }, word_en: "straight ahead", word_en_plural: "straight ahead", category: "directions" },
  
  // PERSONAL PRONOUNS (keeping plural same as singular)
  { word_de: "ich", forms: { plural: null }, word_en: "I", word_en_plural: "I", category: "pronouns" },
  { word_de: "du", forms: { plural: null }, word_en: "you (singular)", word_en_plural: "you (singular)", category: "pronouns" },
  { word_de: "er", forms: { plural: null }, word_en: "he", word_en_plural: "he", category: "pronouns" },
  { word_de: "sie", forms: { plural: null }, word_en: "she", word_en_plural: "she", category: "pronouns" },
  { word_de: "es", forms: { plural: null }, word_en: "it", word_en_plural: "it", category: "pronouns" },
  { word_de: "wir", forms: { plural: null }, word_en: "we", word_en_plural: "we", category: "pronouns" },
  { word_de: "ihr", forms: { plural: null }, word_en: "you (plural)", word_en_plural: "you (plural)", category: "pronouns" },
  { word_de: "Sie", forms: { plural: null }, word_en: "you (formal)", word_en_plural: "you (formal)", category: "pronouns" },
  { word_de: "sie", forms: { plural: null }, word_en: "they", word_en_plural: "they", category: "pronouns" },
  
  // QUESTION WORDS (keeping plural same as singular)
  { word_de: "wer", forms: { plural: null }, word_en: "who", word_en_plural: "who", category: "questions" },
  { word_de: "was", forms: { plural: null }, word_en: "what", word_en_plural: "what", category: "questions" },
  { word_de: "wo", forms: { plural: null }, word_en: "where", word_en_plural: "where", category: "questions" },
  { word_de: "wann", forms: { plural: null }, word_en: "when", word_en_plural: "when", category: "questions" },
  { word_de: "warum", forms: { plural: null }, word_en: "why", word_en_plural: "why", category: "questions" },
  { word_de: "wie", forms: { plural: null }, word_en: "how", word_en_plural: "how", category: "questions" },
  { word_de: "wie viel", forms: { plural: null }, word_en: "how much", word_en_plural: "how much", category: "questions" },
  { word_de: "wie viele", forms: { plural: null }, word_en: "how many", word_en_plural: "how many", category: "questions" }
];
