const WORDS = [
  { word_de: "das Abendessen", forms: { plural: null }, word_en: "dinner", category: "food" },
  { word_de: "die Altstadt", forms: { plural: "Altstädte" }, word_en: "old town", category: "places" },
  { word_de: "die Ampel", forms: { plural: "Ampeln" }, word_en: "traffic light", category: "objects" },
  { word_de: "der Apfel", forms: { plural: "die Äpfel" }, word_en: "apple", category: "food" },
  { word_de: "der April", forms: { plural: null }, word_en: "April", category: "time" },
  { word_de: "der Architekt", forms: { plural: "Architekten" }, word_en: "architect", category: "jobs" },
  { word_de: "die Architektin", forms: { plural: "Architektinnen" }, word_en: "architect", category: "jobs" },
  { word_de: "der Arzt", forms: { plural: "Ärzte" }, word_en: "doctor", category: "jobs" },
  { word_de: "die Ärztin", forms: { plural: "Ärztinnen" }, word_en: "doctor", category: "jobs" },
  { word_de: "der August", forms: { plural: null }, word_en: "August", category: "time" },
  { word_de: "die Ausbildung", forms: { plural: "Ausbildungen" }, word_en: "apprenticeship", category: "education" },
  { word_de: "die Ausstellung", forms: { plural: "Ausstellungen" }, word_en: "gallery", category: "places" },
  { word_de: "das Auto", forms: { plural: "Autos" }, word_en: "car", category: "transport" },
  { word_de: "der Automat", forms: { plural: "Automaten" }, word_en: "vendor", category: "objects" },
  { word_de: "der Bahnhof", forms: { plural: "Bahnhöfe" }, word_en: "train station", category: "transport" },
  { word_de: "die Bar", forms: { plural: "Bars" }, word_en: "bar", category: "places" },
  { word_de: "der Baum", forms: { plural: "Bäume" }, word_en: "tree", category: "nature" },
  { word_de: "der Becher", forms: { plural: "Becher" }, word_en: "mug", category: "objects" },
  { word_de: "der Berg", forms: { plural: "Berge" }, word_en: "mountain", category: "nature" },
  { word_de: "das Bett", forms: { plural: "Betten" }, word_en: "bed", category: "objects" },
  { word_de: "die Bibliothek", forms: { plural: "Bibliotheken" }, word_en: "library", category: "places" },
  { word_de: "das Bier", forms: { plural: "Biere" }, word_en: "beer", category: "food" },
  { word_de: "das Bild", forms: { plural: "Bilder" }, word_en: "picture", category: "objects" },
  { word_de: "der Bildschirm", forms: { plural: "Bildschirme" }, word_en: "screen", category: "technology" },
  { word_de: "der Bleistift", forms: { plural: "Bleistifte" }, word_en: "pencil", category: "objects" },
  { word_de: "die Blume", forms: { plural: "Blumen" }, word_en: "flower", category: "nature" },
  { word_de: "der Blumenladen", forms: { plural: "Blumenläden" }, word_en: "flower shop", category: "places" },
  { word_de: "das Boot", forms: { plural: "Boote" }, word_en: "boat", category: "transport" },
  { word_de: "die Brille", forms: { plural: "Brillen" }, word_en: "glasses", category: "objects" },
  { word_de: "das Brot", forms: { plural: "Brote" }, word_en: "bread", category: "food" },
  { word_de: "das Brötchen", forms: { plural: "Brötchen" }, word_en: "small bread", category: "food" },
  { word_de: "der Bruder", forms: { plural: "Brüder" }, word_en: "brother", category: "family" },
  { word_de: "der Brunnen", forms: { plural: "Brunnen" }, word_en: "fountain", category: "objects" },
  { word_de: "das Buch", forms: { plural: "Bücher" }, word_en: "book", category: "objects" },
  { word_de: "die Bürste", forms: { plural: "Bürsten" }, word_en: "brush", category: "objects" },
  { word_de: "der Bus", forms: { plural: "Busse" }, word_en: "bus", category: "transport" },
  { word_de: "die Bushaltestelle", forms: { plural: "Bushaltestellen" }, word_en: "bus stop", category: "transport" },
  { word_de: "die Butter", forms: { plural: null }, word_en: "butter", category: "food" },
  { word_de: "das Café", forms: { plural: "Cafés" }, word_en: "café", category: "places" },
  { word_de: "die Cafeteria", forms: { plural: "Cafeterien" }, word_en: "cafeteria", category: "places" },
  { word_de: "der Computertechniker", forms: { plural: "Computertechniker" }, word_en: "computer engineer", category: "jobs" },
  { word_de: "die Computertechnikerin", forms: { plural: "Computertechnikerinnen" }, word_en: "computer engineer", category: "jobs" },
  { word_de: "die Couch", forms: { plural: "Couches" }, word_en: "couch", category: "objects" },
  { word_de: "das Curry", forms: { plural: "Currys" }, word_en: "curry", category: "food" },
  { word_de: "das Dachgeschoss", forms: { plural: "Dachgeschosse" }, word_en: "attic", category: "places" },
  { word_de: "der Dezember", forms: { plural: null }, word_en: "December", category: "time" },
  { word_de: "der Dienstag", forms: { plural: null }, word_en: "Tuesday", category: "time" },
  { word_de: "die Disco", forms: { plural: "Discos" }, word_en: "disco", category: "places" },
  { word_de: "der Donnerstag", forms: { plural: null }, word_en: "Thursday", category: "time" }
  // … continue this for all 400+ words …
];
